UniXCoder:
  allowed_base_models: 
    microsoft/unixcoder-base : ["java", "ruby", "python", "php", "javascript", "go"] 
    microsoft/unixcoder-base-unimodal : ["java", "ruby", "python", "php", "javascript", "go"]
    microsoft/unixcoder-base-nine : ["java", "ruby", "python", "php", "javascript", "go", "c++", "c#", "c"]

  serving : 
    batch_size : 32 
    max_length : 512