CodeBert:
  base_tokenizer : "microsoft/codebert-base"
  allowed_base_models: 
    microsoft/codebert-base : ["java", "ruby", "python", "php", "javascript", "go"] 
    documatic/codebert-python-finetuned : ["python"]
  serving: 
    default_batch_size : 32
    max_length : 512 

UniXCoder:
  base_tokenizer : "microsoft/unixcoder-base"
  allowed_base_models: 
    microsoft/unixcoder-base : ["java", "ruby", "python", "php", "javascript", "go"] 
    microsoft/unixcoder-base-unimodal : ["java", "ruby", "python", "php", "javascript", "go"]
    microsoft/unixcoder-base-nine : ["java", "ruby", "python", "php", "javascript", "go", "c++", "c#", "c"]
  serving : 
    default_batch_size : 32 
    max_length : 512

Incoder: 
  base_tokenizer : "facebook/incoder-1B"
  allowed_base_models: 
    facebook/incoder-1B : ["c++", "c#", "clojure", "coffee", "golang", "haskell", "objectivec", "javascript", "typescript", "java", "perl", "php", "python", "ruby", "rust", "scala", "shell", "swift", "lua"]  
    facebook/incoder-6B : ["c++", "c#", "clojure", "coffee", "golang", "haskell", "objectivec", "javascript", "typescript", "java", "perl", "php", "python", "ruby", "rust", "scala", "shell", "swift", "lua"]
  serving: 
    default_batch_size : 8 
    max_length : 512 

CodeT5: 
  base_tokenizer : "Salesforce/codet5-base-multi-sum"
  allowed_base_models: 
    Salesforce/codet5-small : ["python", "javascript", "java", "go", "ruby", "go"]
    Salesforce/codet5-base-multi-sum : ["python", "javascript", "java", "go", "ruby", "go"]
    Salesforce/codet5-base : ["python", "javascript", "java", "go", "ruby", "go"]
    Salesforce/codet5-large : ["python", "javascript", "java", "go", "ruby", "go"]
    Salesforce/codet5-large-ntp-py : ["python"]
  serving: 
    default_batch_size : 16
    max_length : 512 
